version: "3.9"
services:
  app:
    build:
      context: .
      target: alpine
    environment:
      DD_AGENT_HOST: agent
      DD_SERVICE: ${DD_SERVICE:-go-dvwa}
      DD_TAGS: ${DD_TAGS}
      DD_ENV: ${DD_ENV:-testing}
      DD_APPSEC_RULES: ${DD_APPSEC_RULES}
    ports:
      - 7777:7777
  agent:
    image: datadog/agent:7.39.1
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ${DD_SITE}
      DD_REMOTE_CONFIGURATION_ENABLED: ${DD_REMOTE_CONFIGURATION_ENABLED}
      DD_HOSTNAME: ${DD_HOSTNAME}
      DD_ENV: ${DD_ENV}
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: ${DD_DOGSTATSD_NON_LOCAL_TRAFFIC}
      DD_REMOTE_CONFIGURATION_ENABLED: ${DD_REMOTE_CONFIGURATION_ENABLED}
      DD_API_KEY: ${DD_API_KEY}
      DD_REMOTE_CONFIGURATION_KEY: ${DD_REMOTE_CONFIGURATION_KEY}
      DD_REMOTE_CONFIGURATION_CONFIG_ROOT: ${DD_REMOTE_CONFIGURATION_CONFIG_ROOT}
      DD_REMOTE_CONFIGURATION_DIRECTOR_ROOT: ${DD_REMOTE_CONFIGURATION_DIRECTOR_ROOT}
      DD_REMOTE_CONFIGURATION_REFRESH_INTERVAL: ${DD_REMOTE_CONFIGURATION_REFRESH_INTERVAL}

    ports:
      - 8125:8125/udp
      - 8126:8126
